#+title: Thesis
#+author: Sergi Simón Balcells


* PROJ RoadMap to write thesis
+ [X] What to include?
+ [X] Sections
** Previous work
[[https://recsi2022.unican.es/wp-content/uploads/2022/10/LibroActas-978-84-19024-14-5.pdf]]

* TODO Abstract
+ [X] Dunno, base it on previous work

An online forum is a platform that enables users to post messages which become available to any
person with access to it. In this article, we focus on forums that preserve the anonymity of a
user while being authenticated. More concretely, in this paper, we improve an existing scheme.

Index terms - cryptography, discussion board, privacy, ring signature

* TODO Introduction
- [X] Forum signature use case
- [X] Signatures schemas: ring and group
- [X] +Previous work+ would be in caveats of the previous approach

Enterprises, city halls, and educators found a way to guarantee anonymous feedback by providing a mailbox
where people could post a message without specifying who it was. This enabled workers, citizens, and students
to provide feedback without any chance of having repercussions for criticizing them. At the same time, as the location of them was inside of the enterprise, city, and educational center, the readers could assert with some
security that the writer was, in fact, an employee, a citizen, and a student.

With the arrival of the Internet, some of these activities could be online, as a remote
office, so it made apparent that there is a need for a security protocol that preserves the
anonymity of the poster while it makes sure that the writer is an authenticated user. This use case
will be referred to as a forum in this paper.

Such a cryptographic system should provide a means to authenticate, so only users can post messages. The users
should remain anonymous, as the identity of the message author is not revealed. Additionally, messages from the same user should remain unlinkable.

For this cryptographic scheme, a Group signature \cite{group} could provide the required security purposes. However, this cryptographic scheme includes a trusted group manager, who can revoke the anonymity of the writer when required. To overcome this difficulty, the protocol described here will use a similar tool, namely, ring signatures \cite{ring}. This does not require its users to trust the entity except for
certificate authorities issuing public key certificates.

* Preliminaries
+ [X] Group signature
+ [X] Ring Signature
+ [X] Internet writer distribution
+ [ ] I think it needs something more.
Before continuing, a few concepts have to be made clear to explain the algorithm, and the caveats of the
previous work. Concretely, both group and ring signatures have to be explained, the distribution that posters
in an Internet forum follow, #+TODO


** Group Signature
Group signatures \cite{group} are a cryptographic protocol that lets a user sign as a group of users. The
use case for this protocol is enterprises or city halls, where one worker could make an official statement
without needing a centralized user for everyone or specifying who in the group has signed. This is a better
approach to publishing an official statement, as this needs a centralized user, which attacks through social engineering, such as fishing, could make more damage than a non centralized user. Nevertheless, it needs a trusted middleman to encrypt securely the message, and this middleman knows who has posted the message. For this specific reason, this protocol can not be used in our public encryption, as the sole purpose of signing the message is to make sure that the centralized forum *does not know* who has posted it.

** Ring Signature
On the other hand, ring signatures \cite{ring} provides the same as group signatures without the middleman, and as such is the perfect cryptographic protocol to base the forum cryptographic system. The idea is that every message is signed by a subgroup of the forum users, such as 8 users. This provides anonymity of the user of $\frac{1}{8}$ chances of being the real original poster. Additionally, efficient ring signatures exist \cite{ring-rsa}, where the size of the public key does not depend on the size of the group signature, making it painless to improve security by providing a larger public key for encryption.

Then, the problem for this algorithm is choosing the users that should fill the space of signatures. In the next subsection, we will discuss the which distribution does the internet posts follow.
** Internet post distribution
The reality between the distribution of the messages and the posters makes such a random
assignment impossible to hold. Posters have an empirically 90-9-1 percent approach to posting, where the 90%
of the users barely post (lurkers), 1% of the users post most of the content (superusers), and 9% percent of
the users post more regularly but not as outlying as the 1% (users). The \cite{zipf} article analyzes this
distribution, where it explains that the known Zipf law adapts well to simulate this posting scenario.

Using a randomly assigned group and knowing that the distribution follows the Zipf law, makes the superusers
anonymity, that is, the number of signatures that a user appears divided by the number of messages posted, close to one, which in turn means that the most of its signatures are also their posts. This makes it not secure to use a randomly assigned group approach for signing in to an online forum.



* TODO Caveats of previous approach
+ [X] bad start makes different for weight
+ [ ] bad if user changes habits
  + [ ] paper for change in user habits
+ [X] depending on weight, bad for lurker or bad for super users
+ [X] window of last n messages
+ [X] simplified complexity if the forum grows larger
+ [X] computes weight based on that, so there is a maximum weight possible

The previous algorithm \cite{recsi} querried all the previous messages that has been sent in the forum and attaches a weight depending on the number of messages. The thought is that the algorithm will adapt to the those users that have a large amount of signatures as superusers and give them more weight, those solving the problem that a random approach had. The problem is the initial number of messages, as most weights sky-rocket the number of signatures, so that the anonymity in the super users is stonishigly high on average, but close to non-existance for lurkers that started sending messages later on. The solution was to increase the initial message weight, so that the weight added for signatures didn't matter as much, but the sheer amount of signatures on the superuser would still provide a better anonymity for them.

This solution was inconvenient because it sacrificed the anonymity of both lurkers and superusers. It was discussed that a time weight, that is, the weight of a signature is decreased with time.

Another problem is the lack of scalability. As more messages are sent in the forum, more costly is to send another message, as you have to add all the weights to be able to sign. This is not a problem with smaller forums, but consider that this forum is used in a big city with millions of habitants. It could potentially mean that after some years, it is not possible to post anymore. For this reason, it was argued that instead of decreasing the weight with time, creating a window of the last $n$ signatures and computing the weight with them, would be more efficient. Additionaly, as the window is limited, there is a limit in the weight that the user can carry, possibly making the algorithm solve the snowballing effect.

Finally, #+TODO change in user habits The purpose of this paper is to simulate the window approach and compare the anonymity to the previous algorithm.

* Methodology
The anonymity of a user is declared as the number of messages sent divided by the number of messages signed. This will be the most important value that we can use to assert how strong is the cryptosystem. But, let's showcase that it is not valuable for a specific user. If one user has a low anonymity, but, with the same number of signatures, most users have a high anonymity, then it's impossible to discern which is the low anonymity user, as the attacker would a priori only have the signatures as a way to tell which user posted. As such, it matters the average or the median of anonymity in a group of users with similar number of signatures.

Now, in a simulation we can find the distribution of signatures. Although the messages crearly receive a Zipf distribution, the final distribution on signatures should be more normalized. A quick execution

* TODO Results
+ [ ] add graphic distribution of anonymity
  + [ ] explain that if users have the same amount of signatures but one has
    low anonymity while other high, then you have less chance to get the correct user
+ [ ] add caveat of first message
  + [ ] explain that in simulations, it has even better anonymity than normal
+ [ ] Add boxplots of anonymity of users.

* TODO Conclusions
+ [ ] Window is a superior approach to forum schemes.
* TODO Acknowledgements
+ [ ] I don't know if I have any
* TODO References
+ [ ] The eight references of my life.
+ [ ] delete this, as the latex block takes care already


#+begin_src latex
\bibliography{bib}
\bibliographystyle{ieeetr}
#+end_src
